# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nro_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(default=b'', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estreno', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('genero', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='videoclub.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alquiler', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclub.Cliente')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoclub.Pelicula')),
            ],
        ),
    ]
